In [3]:
import numpy as np
import sympy

# Homework 1a
### Jake Callahan
## Problem 2

In [4]:
P = np.array([[2,3,1],[1,2,1],[1,1,1]])

### a)
Find $P^{-1}$, if it exists

#### Solution:

In [7]:
P_inv = np.linalg.inv(P)
print('P inverse:')
print(P_inv)

P inverse:
[[ 1. -2.  1.]
 [ 0.  1. -1.]
 [-1.  1.  1.]]


### b)
Suppose that in the standard basis a vector $x$ is given by $\begin{bmatrix}2 \\ 1 \\ 4\end{bmatrix}$. Find the representation of $x$ with respect to the basis defined by $P$.
#### Solution:
If $x = Px_b$, then $x_b = P^{-1}x$:

In [10]:
x = np.array([2,1,4])
x_b = P_inv @ x
print('x in P basis:')
print(x_b)

x in P basis:
[ 4. -3.  3.]


## Problem 6
Consider the matrix
      $A = \begin{bmatrix} -1 & 2 & 3 \\ 4 & -5 & 6 \\ 7 & 8 & -9\end{bmatrix}$
      
a) Find a matrix $M$ such that $M^{-1} A M$ is diagonal  
b) Does there exist a matrix $M$ that can diagonalize any square matrix $A$? Explain.   
c) Determine the characteristic polynomical of $A$.

### a)
#### Solution

In [18]:
A = np.array([[-1,2,3],[4,-5,6],[7,8,-9]])
evals, evecs = np.linalg.eig(A)
print('The matrix M is given by:')
print(evecs)

The matrix M is given by:
[[-0.52501906 -0.6018843  -0.1182433 ]
 [-0.5918207   0.70453221 -0.49287447]
 [-0.6116398   0.37599157  0.86202858]]


### b)
#### Solution
There is no such M because a singular matrix cannot be diagonalized.

### c)
The characteristic polynomial is the polynomial whose roots are the eigenvalues calculated above. This can also be found by taking the determinant of $A - \lambda I$. We compute this below:

In [28]:
M = sympy.Matrix([[-1,2,3],[4,-5,6],[7,8,-9]])
λ = sympy.symbols('λ')
poly = M.charpoly(λ)
print('The characteristic polynomial is:')
poly

The characteristic polynomial is:


PurePoly(λ**3 + 15*λ**2 - 18*λ - 360, λ, domain='ZZ')